version: '3'

services:
    app:
        build: 
            context: .
            dockerfile: .docker/Dockerfile
        volumes:
          - .:/app
        working_dir: /app
        ports:
          - "1234:8080"
          - "3000:3000"
        tty: true
        environment: 
            - CHOKIDAR_USEPOLLING=true #auto reload